// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRgyEB5o6tDazlY_a3xfxdUMge1fpMZDw',
    appId: '1:994334511147:web:5c2e798582eb97026e9a6e',
    messagingSenderId: '994334511147',
    projectId: 'todoapp-36d71',
    authDomain: 'todoapp-36d71.firebaseapp.com',
    storageBucket: 'todoapp-36d71.appspot.com',
    measurementId: 'G-7NSPGCLGT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHlgDUTc2vS3OT0lqHCIq5IDS09x_jNH8',
    appId: '1:994334511147:android:878b86bdc89c79676e9a6e',
    messagingSenderId: '994334511147',
    projectId: 'todoapp-36d71',
    storageBucket: 'todoapp-36d71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB95yj8d85_Er7t3-x9PNFIabEynr4v1Ts',
    appId: '1:994334511147:ios:a0727201edb868fd6e9a6e',
    messagingSenderId: '994334511147',
    projectId: 'todoapp-36d71',
    storageBucket: 'todoapp-36d71.appspot.com',
    iosClientId: '994334511147-79qr5ef8jrfhuti17fgamat6nnfdkqsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB95yj8d85_Er7t3-x9PNFIabEynr4v1Ts',
    appId: '1:994334511147:ios:87f7d431aa3e6aa76e9a6e',
    messagingSenderId: '994334511147',
    projectId: 'todoapp-36d71',
    storageBucket: 'todoapp-36d71.appspot.com',
    iosClientId: '994334511147-3155008vmj2kp34rcf66mn72iofntv9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
